### ISSUE TITLE
Update Problem

### ISSUE THREAD

**Issue by SduyXD** [olmokramer/atom-dark-flat-ui#2]
Hi!
Atom tells me I have the version 0.4.4 but I have the 0.8.2, I do not know what's going on here, update and it keeps telling me there's a new version

I Like this Ui Theme

**Comment by olmokramer** [comment]
First, thanks for the nice words :)

Have you tried uninstalling the theme completely, and installing it again? Also what version of Atom are you using?

**Comment by olmokramer** [comment]
And what does the `package.json` have in the `version` field?

**Comment by SduyXD** [comment]
Yes the package.json have version 0.8.2 i am using Atom 0.175.0,
i will try uninstalling and installing again

**Comment by SduyXD** [comment]
Just not working for me

**Comment by SduyXD** [comment]
There are some screenshots:

http://cl.ly/image/0B1N3Q3x2J3A
http://cl.ly/image/2U3S0H0V0b1m

**Comment by olmokramer** [comment]
That's very odd. I think I remember now I had that same issue with another package, and it went away when I updated Atom. Seemed nothing to do with the package, but with Atom. Let's see if we can find some information about it.

**Comment by olmokramer** [comment]
If you run `apm list --themes --installed`, does it list the theme with the correct version?

**Comment by SduyXD** [comment]
yes 0.8.2

**Comment by SduyXD** [comment]
Mmm i dont known what happened here but it's fixed now :)

**Comment by olmokramer** [comment]
Hmm....... Anyway, glad to hear it's fixed :)
