### ISSUE TITLE
Icons

### ISSUE THREAD

**Issue by tnguyen14** [olmokramer/atom-dark-flat-ui#3]
How do I get the file icons like your screenshot? I installed your theme but the files still have the default icon.

**Comment by olmokramer** [comment]
It's a package called [file-icons](https://atom.io/packages/file-icons)

**Comment by tnguyen14** [comment]
Many thanks!

**Comment by olmokramer** [comment]
You're welcome :)
I forgot to mention there are other packages that do the same thing: [file-type-icons](https://atom.io/packages/file-type-icons) and [file-icons-supplement](https://atom.io/packages/file-icons-supplement). I just liked the first one the most
